### ISSUE TITLE
Interruptable containers

### ISSUE THREAD

**Issue by slindley** [effect-handlers/effect-handlers-bench#7]
For my own convenience I changed the make files to make the containers interruptable. This is definitely what I want when running them on my own system (it also allows hyperfine to display its progress bars). However it breaks the CI as the CI's input device is not a TTY. I guess the solution is to have two different ways of running the docker images: one for the CI and another for running locally.

**Comment by kayceesrk** [comment]
Links is still failing: https://github.com/effect-handlers/effect-handlers-bench/actions/runs/1090253854.

**Comment by dhil** [comment]
It seems to halt on tzdata configuration. We may have to explicitly symlink some timezone or pipe some input to apt.

**Comment by kayceesrk** [comment]
We should try this: https://stackoverflow.com/questions/8671308/non-interactive-method-for-dpkg-reconfigure-tzdata

**Comment by dhil** [comment]
Thanks. I managed to build the container locally now. I am pushing it to Dockerhub as I am typing this message.
